name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_extensions: xdebug apcu redis

      - name: Pre-commit checks
        uses: pre-commit/action@v3.0.1

      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_extensions: xdebug apcu redis
          args: --coverage-text
        env:
          XDEBUG_MODE: coverage
